package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.PlayerPosition;
import org.mybatis.cdi.Mapper;

@Mapper
public interface PlayerPositionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLAYER_POSITION
     *
     * @mbg.generated Sat Apr 10 23:00:46 EEST 2021
     */
    int insert(PlayerPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLAYER_POSITION
     *
     * @mbg.generated Sat Apr 10 23:00:46 EEST 2021
     */
    List<PlayerPosition> selectAll();
}