package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Position;
import org.mybatis.cdi.Mapper;

@Mapper
public interface PositionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.POSITION
     *
     * @mbg.generated Sat Apr 10 23:00:46 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.POSITION
     *
     * @mbg.generated Sat Apr 10 23:00:46 EEST 2021
     */
    int insert(Position record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.POSITION
     *
     * @mbg.generated Sat Apr 10 23:00:46 EEST 2021
     */
    Position selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.POSITION
     *
     * @mbg.generated Sat Apr 10 23:00:46 EEST 2021
     */
    List<Position> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.POSITION
     *
     * @mbg.generated Sat Apr 10 23:00:46 EEST 2021
     */
    int updateByPrimaryKey(Position record);
}