package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Subject;
import org.mybatis.cdi.Mapper;

@Mapper
public interface SubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SUBJECT
     *
     * @mbg.generated Sat Apr 17 17:20:05 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SUBJECT
     *
     * @mbg.generated Sat Apr 17 17:20:05 EEST 2021
     */
    int insert(Subject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SUBJECT
     *
     * @mbg.generated Sat Apr 17 17:20:05 EEST 2021
     */
    Subject selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SUBJECT
     *
     * @mbg.generated Sat Apr 17 17:20:05 EEST 2021
     */
    List<Subject> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SUBJECT
     *
     * @mbg.generated Sat Apr 17 17:20:05 EEST 2021
     */
    int updateByPrimaryKey(Subject record);
}