package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Universitygroup;
import org.mybatis.cdi.Mapper;

@Mapper
public interface UniversitygroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.UNIVERSITYGROUP
     *
     * @mbg.generated Sat Apr 17 17:22:45 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.UNIVERSITYGROUP
     *
     * @mbg.generated Sat Apr 17 17:22:45 EEST 2021
     */
    int insert(Universitygroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.UNIVERSITYGROUP
     *
     * @mbg.generated Sat Apr 17 17:22:45 EEST 2021
     */
    Universitygroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.UNIVERSITYGROUP
     *
     * @mbg.generated Sat Apr 17 17:22:45 EEST 2021
     */
    List<Universitygroup> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.UNIVERSITYGROUP
     *
     * @mbg.generated Sat Apr 17 17:22:45 EEST 2021
     */
    int updateByPrimaryKey(Universitygroup record);
}