package lt.vu.mybatis.model;

import lt.vu.entities.Position;

import java.util.ArrayList;
import java.util.List;

public class Player {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLAYER.ID
     *
     * @mbg.generated Sat Apr 10 22:46:56 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLAYER.NUMBER
     *
     * @mbg.generated Sat Apr 10 22:46:56 EEST 2021
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLAYER.FIRST_NAME
     *
     * @mbg.generated Sat Apr 10 22:46:56 EEST 2021
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLAYER.LAST_NAME
     *
     * @mbg.generated Sat Apr 10 22:46:56 EEST 2021
     */
    private String lastName;

    private List<Position> positions = new ArrayList<>();

    private Team team;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLAYER.TEAM_ID
     *
     * @mbg.generated Sat Apr 10 22:46:56 EEST 2021
     */
    private Integer teamId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLAYER.ID
     *
     * @return the value of PUBLIC.PLAYER.ID
     *
     * @mbg.generated Sat Apr 10 22:46:56 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLAYER.ID
     *
     * @param id the value for PUBLIC.PLAYER.ID
     *
     * @mbg.generated Sat Apr 10 22:46:56 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLAYER.NUMBER
     *
     * @return the value of PUBLIC.PLAYER.NUMBER
     *
     * @mbg.generated Sat Apr 10 22:46:56 EEST 2021
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLAYER.NUMBER
     *
     * @param number the value for PUBLIC.PLAYER.NUMBER
     *
     * @mbg.generated Sat Apr 10 22:46:56 EEST 2021
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLAYER.FIRST_NAME
     *
     * @return the value of PUBLIC.PLAYER.FIRST_NAME
     *
     * @mbg.generated Sat Apr 10 22:46:56 EEST 2021
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLAYER.FIRST_NAME
     *
     * @param firstName the value for PUBLIC.PLAYER.FIRST_NAME
     *
     * @mbg.generated Sat Apr 10 22:46:56 EEST 2021
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLAYER.LAST_NAME
     *
     * @return the value of PUBLIC.PLAYER.LAST_NAME
     *
     * @mbg.generated Sat Apr 10 22:46:56 EEST 2021
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLAYER.LAST_NAME
     *
     * @param lastName the value for PUBLIC.PLAYER.LAST_NAME
     *
     * @mbg.generated Sat Apr 10 22:46:56 EEST 2021
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLAYER.TEAM_ID
     *
     * @return the value of PUBLIC.PLAYER.TEAM_ID
     *
     * @mbg.generated Sat Apr 10 22:46:56 EEST 2021
     */
    public Integer getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLAYER.TEAM_ID
     *
     * @param teamId the value for PUBLIC.PLAYER.TEAM_ID
     *
     * @mbg.generated Sat Apr 10 22:46:56 EEST 2021
     */
    public void setTeamId(Integer teamId) {
        this.teamId = teamId;
    }
}