package lt.vu.mybatis.model;

public class PlayerPosition {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLAYER_POSITION.POSITION_ID
     *
     * @mbg.generated Sat Apr 10 23:00:46 EEST 2021
     */
    private Integer positionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLAYER_POSITION.PLAYER_ID
     *
     * @mbg.generated Sat Apr 10 23:00:46 EEST 2021
     */
    private Integer playerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLAYER_POSITION.POSITION_ID
     *
     * @return the value of PUBLIC.PLAYER_POSITION.POSITION_ID
     *
     * @mbg.generated Sat Apr 10 23:00:46 EEST 2021
     */
    public Integer getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLAYER_POSITION.POSITION_ID
     *
     * @param positionId the value for PUBLIC.PLAYER_POSITION.POSITION_ID
     *
     * @mbg.generated Sat Apr 10 23:00:46 EEST 2021
     */
    public void setPositionId(Integer positionId) {
        this.positionId = positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLAYER_POSITION.PLAYER_ID
     *
     * @return the value of PUBLIC.PLAYER_POSITION.PLAYER_ID
     *
     * @mbg.generated Sat Apr 10 23:00:46 EEST 2021
     */
    public Integer getPlayerId() {
        return playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLAYER_POSITION.PLAYER_ID
     *
     * @param playerId the value for PUBLIC.PLAYER_POSITION.PLAYER_ID
     *
     * @mbg.generated Sat Apr 10 23:00:46 EEST 2021
     */
    public void setPlayerId(Integer playerId) {
        this.playerId = playerId;
    }
}