package lt.vu.mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class Position {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.POSITION.ID
     *
     * @mbg.generated Sat Apr 10 23:00:46 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.POSITION.NAME
     *
     * @mbg.generated Sat Apr 10 23:00:46 EEST 2021
     */
    private String name;
    private List<Player> players = new ArrayList<>();

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.POSITION.ID
     *
     * @return the value of PUBLIC.POSITION.ID
     *
     * @mbg.generated Sat Apr 10 23:00:46 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.POSITION.ID
     *
     * @param id the value for PUBLIC.POSITION.ID
     *
     * @mbg.generated Sat Apr 10 23:00:46 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.POSITION.NAME
     *
     * @return the value of PUBLIC.POSITION.NAME
     *
     * @mbg.generated Sat Apr 10 23:00:46 EEST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.POSITION.NAME
     *
     * @param name the value for PUBLIC.POSITION.NAME
     *
     * @mbg.generated Sat Apr 10 23:00:46 EEST 2021
     */
    public void setName(String name) {
        this.name = name;
    }
}