package lt.vu.mybatis.model;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.ID
     *
     * @mbg.generated Sat Apr 17 17:20:05 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.NUMBER
     *
     * @mbg.generated Sat Apr 17 17:20:05 EEST 2021
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.FIRST_NAME
     *
     * @mbg.generated Sat Apr 17 17:20:05 EEST 2021
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.LAST_NAME
     *
     * @mbg.generated Sat Apr 17 17:20:05 EEST 2021
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.GROUP_ID
     *
     * @mbg.generated Sat Apr 17 17:20:05 EEST 2021
     */
    private Integer groupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.ID
     *
     * @return the value of PUBLIC.STUDENT.ID
     *
     * @mbg.generated Sat Apr 17 17:20:05 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.ID
     *
     * @param id the value for PUBLIC.STUDENT.ID
     *
     * @mbg.generated Sat Apr 17 17:20:05 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.NUMBER
     *
     * @return the value of PUBLIC.STUDENT.NUMBER
     *
     * @mbg.generated Sat Apr 17 17:20:05 EEST 2021
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.NUMBER
     *
     * @param number the value for PUBLIC.STUDENT.NUMBER
     *
     * @mbg.generated Sat Apr 17 17:20:05 EEST 2021
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.FIRST_NAME
     *
     * @return the value of PUBLIC.STUDENT.FIRST_NAME
     *
     * @mbg.generated Sat Apr 17 17:20:05 EEST 2021
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.FIRST_NAME
     *
     * @param firstName the value for PUBLIC.STUDENT.FIRST_NAME
     *
     * @mbg.generated Sat Apr 17 17:20:05 EEST 2021
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.LAST_NAME
     *
     * @return the value of PUBLIC.STUDENT.LAST_NAME
     *
     * @mbg.generated Sat Apr 17 17:20:05 EEST 2021
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.LAST_NAME
     *
     * @param lastName the value for PUBLIC.STUDENT.LAST_NAME
     *
     * @mbg.generated Sat Apr 17 17:20:05 EEST 2021
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.GROUP_ID
     *
     * @return the value of PUBLIC.STUDENT.GROUP_ID
     *
     * @mbg.generated Sat Apr 17 17:20:05 EEST 2021
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.GROUP_ID
     *
     * @param groupId the value for PUBLIC.STUDENT.GROUP_ID
     *
     * @mbg.generated Sat Apr 17 17:20:05 EEST 2021
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }
}