package lt.vu.mybatis.model;

public class Subject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SUBJECT.ID
     *
     * @mbg.generated Sat Apr 17 17:20:05 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SUBJECT.NAME
     *
     * @mbg.generated Sat Apr 17 17:20:05 EEST 2021
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SUBJECT.ID
     *
     * @return the value of PUBLIC.SUBJECT.ID
     *
     * @mbg.generated Sat Apr 17 17:20:05 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SUBJECT.ID
     *
     * @param id the value for PUBLIC.SUBJECT.ID
     *
     * @mbg.generated Sat Apr 17 17:20:05 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SUBJECT.NAME
     *
     * @return the value of PUBLIC.SUBJECT.NAME
     *
     * @mbg.generated Sat Apr 17 17:20:05 EEST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SUBJECT.NAME
     *
     * @param name the value for PUBLIC.SUBJECT.NAME
     *
     * @mbg.generated Sat Apr 17 17:20:05 EEST 2021
     */
    public void setName(String name) {
        this.name = name;
    }
}